#!/bin/sh

# 设置主机名
uci set system.@system[0].hostname='OpenWRT'
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].zonename='Asia/Shanghai'
uci commit system

# 设置默认主题
if [ -d /www/luci-static/argon ]; then
    uci set luci.main.mediaurlbase='/luci-static/argon'
else
    uci set luci.main.mediaurlbase='/luci-static/bootstrap'
fi
uci commit luci

# 确保 uhttpd 监听
uci set uhttpd.main.listen_http='0.0.0.0:80'
uci add_list uhttpd.main.listen_http='[::]:80'
uci set uhttpd.main.listen_https='0.0.0.0:443'
uci add_list uhttpd.main.listen_https='[::]:443'
uci commit uhttpd

# LAN IP
uci set network.lan.ipaddr='192.168.3.1'
uci set network.lan.proto='static'
uci set network.lan.netmask='255.255.255.0'
uci commit network

exit 0
